baseurl = "/"
title = "ANOOP CHANDRAN"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Portfolio Website"
  copyright = "&copy;2016 anoopc.netlify.com"
  sidebarAbout = [
    "I am a Frontend Developer and graphic designer with more than 5 years of experience.",
    "Originally from India, currently based in Hong Kong."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/anoop.chandran.hk"
  googleplus    = "https://plus.google.com/u/0/107267773390951989950"
  email         = "mailto.anoopc@gmail.com"
  twitter       = "https://twitter.com/iamanoopc"
  linkedin      = "https://www.linkedin.com/in/anoop-chandran-18290a91/"
  stackoverflow = "https://stackoverflow.com/users/4531869/anoop-chandran"
  github        = "https://github.com/iamanoopc"
